trigger:
  branches:
    include:
      - main
      - industry-insights
  paths:
    include:
      - screen/src/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - screen/src/**

jobs:
- job: DockerBuildRun
  pool:
    name: ScreenAgent
  steps:
  - checkout: self

  - script: docker stop screen || true
    displayName: Stop Docker container

  - script: docker system prune -a -f
    displayName: Prune Docker system

  - script: killall chromium-browser || true
    displayName: Kill Chromium process

  - script: docker build --build-arg REACT_APP_TOKEN=$(REACT_APP_TOKEN) -t screen -f screen/Dockerfile .
    displayName: Docker Build

  - script: docker run -e REACT_APP_TOKEN=$(REACT_APP_TOKEN) -d --restart=always --name screen -p 3000:3000 screen
    displayName: Docker Run

  - script: chromium-browser --kiosk http://localhost:3000 &
    displayName: Open Chromium browser
