trigger:
  - main

pr:
  - main

jobs:
- job: DockerBuildRun
  pool:
    name: Default
  steps:
  - checkout: self
  
  # - script: docker-compose2 down
  - script: docker stop screen || true
    displayName: Stop Docker container

  - script: docker system prune -a -f
    displayName: Prune Docker system

  - script: killall chromium-browser || true
    displayName: Kill Chromium process

  # - script: docker-compose build
  - script: docker build -t screen -f screen/Dockerfile .
    displayName: Docker Build

  # - script: docker-compose up -d
  - script: docker run -d --restart=always --name screen -p 3000:3000 screen
    displayName: Docker Run

  - script: chromium-browser --kiosk http://localhost:3000 &
    displayName: Open Chromium browser
